load("//platforms:apple.bzl", "APPLE_ONLY")
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_test")

swift_test(
    name = "HermoLogicTests",
    srcs = glob(["*.swift"]),
    target_compatible_with = APPLE_ONLY,
    size = "small",
    module_name = "HermoLogicTests",
    deps = [
        "//ios/Sources/HermoLogic",
    ],
)
